### ISSUE TITLE
Rotary Pintograph + more wheels + p5 js

### ISSUE THREAD

**Issue by felipeinfantino** [michaldudak/pintograph#1]
Hi, first of all thank you so much for sharing this project, it is very interesting and very pleasent. Its great.

Regarding this project I have 3 Questions: 

1. Is it possible to make the rotary pintograph with this project? I mean to rotate where the pen is drawing, like in the last part of http://www.fxmtech.com/harmonog.html 

2. Is there a way to add more than two weels ? Something like this simulation https://www.facebook.com/watch/?v=781716872198726 

3. I am interested to recreate this project in p5 js , do you think you could briefly guide me on how to achieve this ? I mean there is a lot of Math and physics involved that I dont really understand, but since you already done that, I think it would be great if we could talk or you could write some kind of explanation on how it actually works.

**Comment by michaldudak** [comment]
Hi, I'm sorry I respond after such a long time. I must have missed the notification and I haven't been active on this project during the last few months. Answering your questions:
1. Yes, a rotary pintograph is possible by placing both wheels on a larger wheel. This way, the whole pintograph rotates (instead of rotating the paper as in the real-world example), but the effect is the same.
2. It not possible as of now. It's an interesting idea, though, and shouldn't be hard to implement. I'll consider it when I get back to this project.
3. I took all the descriptions and explanations from sites I mention in readme. The math may look complicated because of matrix operations, but it can be done in a more "traditional" way. Wheels are pretty much simple - during every update I calculate the position and angle of the mount point based on the rotation of the wheel. The V-arm calculates the position of its mount point based on the distance of points it it mounted to. The X-arm is a bit more complicated as it is an extension of the V-arm.

If you have any specific questions or problems understanding a particular piece of code, I'll try to help.

**Comment by michaldudak** [comment]
Actually, I think it should be possible to recreate the multi-wheel setup you linked. You would have to use wheels and X-arms and attach some of the arms to the other. I'll try to create a demo for this.
